spring:
  jmx:
    default-domain: ${spring.application.name}

backbase:
  security:
    mtls:
      paths: /integration-api/**

sso:
  jwt:
    internal:
      type: signed
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY