spring:
  jmx:
    default-domain: ${spring.application.name}
  activemq:
    broker-url: ${activemq.url:tcp://localhost:61616}

logging:
  level:
    root: WARN
    com.backbase: WARN

backbase:
  billpay: 
    provider:
      url: ${billpay.provider.url}
      clientAppText: ${billpay.provider.clientAppText}
      clientAppVersion: ${billpay.provider.clientAppVersion}
      sponsorId: ${billpay.provider.sponsorId}

sso:
  jwt:
    internal:
      type: signed
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY