server:
  port: 8098
  
logging:
  level:
    com.backbase: DEBUG
    
spring:
  activemq:
    broker-url: tcp://localhost:61616

backbase:
  billpay: 
    provider:
      url: http://localhost:1080/fiserv
      clientAppText: billpay
      clientAppVersion: 1.0
      sponsorId: BankA
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/registry/eureka/